services:
#    hchc.example:
#        class: HC\HCBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    hchc.listener.entitylistener:
        class: HC\HCBundle\Entity\EntityListener
        arguments: [@service_container]
        tags:
           - { name: doctrine.event_listener, event: postPersist }
           - { name: doctrine.event_listener, event: preUpdate }
           - { name: doctrine.event_listener, event: postUpdate }
           - { name: doctrine.event_listener, event: preRemove }