HC\HCBundle\Entity\Notacita:
    type: entity
    table: notaCita
    indexes:
        idCita:
            columns:
                - idCita
        idHci:
            columns:
                - idHci
    id:
        idnotacita:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idNotaCita
            generator:
                strategy: IDENTITY
    fields:
        presionarterial:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: presionArterial
        alturapaciente:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: alturaPaciente
        pesopaciente:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: pesoPaciente
        frecuenciacardiaca:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
            column: frecuenciaCardiaca
        temperatura:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
    manyToOne:
        idhci:
            targetEntity: Hci
            cascade: {  }
            mappedBy: null
            inversedBy: notacita
            joinColumns:
                idHci:
                    referencedColumnName: idHci
            orphanRemoval: false
    oneToMany:
        prescripcion:
            targetEntity: Prescripcion
            cascade: ["persist","remove"]
            mappedBy: idnotacita
        diagnostico:
            targetEntity: Diagnostico
            cascade: ["persist","remove"]
            mappedBy: idnotacita
        referencia:
            targetEntity: Referencia
            cascade: ["persist","remove"]
            mappedBy: idnotacita
    oneToOne:
        idcita:
            targetEntity: Cita
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCita:
                    referencedColumnName: idCita
            orphanRemoval: false
    lifecycleCallbacks: {  }
