HC\HCBundle\Entity\Notascitahci:
    type: entity
    table: notasCitaHci
    indexes:
        idNotaCita:
            columns:
                - idNotaCita
        idHci:
            columns:
                - idHci
    id:
        idnotaschci:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idNotasCHci
            generator:
                strategy: IDENTITY
    manyToOne:
        idnotacita:
            targetEntity: Notacita
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idNotaCita:
                    referencedColumnName: idNotaCita
            orphanRemoval: false
        idhci:
            targetEntity: Hci
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idHci:
                    referencedColumnName: idHci
            orphanRemoval: false
    lifecycleCallbacks: {  }
