HC\HCBundle\Entity\Prescripcion:
    type: entity
    table: prescripcion
    indexes:
        idNotaCita:
            columns:
                - idNotaCita
        idUsuario:
            columns:
                - idUsuario
    id:
        idprescripcion:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idPrescripcion
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: datetime
            nullable: false
            comment: ''
        nombre:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        instrucciones:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        idnotacita:
            targetEntity: Notacita
            cascade: {  }
            mappedBy: null
            inversedBy: prescripcion
            joinColumns:
                idNotaCita:
                    referencedColumnName: idNotaCita
            orphanRemoval: false
    oneToOne:
        idusuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUsuario:
                    referencedColumnName: idUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
