HC\HCBundle\Entity\Prescripcionmedico:
    type: entity
    table: prescripcionMedico
    indexes:
        idMedico:
            columns:
                - idMedico
    id:
        idpresmedico:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idPresMedico
            generator:
                strategy: IDENTITY
    fields:
        idprescripcion:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: idPrescripcion
    manyToOne:
        idmedico:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idMedico:
                    referencedColumnName: idUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
