HC\HCBundle\Entity\Privilegio:
    type: entity
    table: privilegio
    id:
        idprivilegio:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idPrivilegio
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
