HC\HCBundle\Entity\Referencia:
    type: entity
    table: referencia
    indexes:
        idNotaCita:
            columns:
                - idNotaCita
        idUsuario:
            columns:
                - idUsuario
    id:
        idreferencia:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idReferencia
            generator:
                strategy: IDENTITY
    fields:
        nombredoctor:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            column: nombreDoctor
        descripcion:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        fecha:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:    
        idnotacita:
            targetEntity: Notacita
            cascade: {  }
            mappedBy: null
            inversedBy: referencia
            joinColumns:
                idNotaCita:
                    referencedColumnName: idNotaCita
            orphanRemoval: false
    oneToOne:
        idusuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUsuario:
                    referencedColumnName: idUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
