HC\HCBundle\Entity\Tipoestado:
    type: entity
    table: tipoEstado
    id:
        idtipoestado:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idTipoEstado
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
