HC\HCBundle\Entity\Visitapaciente:
    type: entity
    table: visitaPaciente
    indexes:
        idCita:
            columns:
                - idCita
        idPaciente:
            columns:
                - idPaciente
    id:
        idvisitapaciente:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idVisitaPaciente
            generator:
                strategy: IDENTITY
    manyToOne:
        idcita:
            targetEntity: Cita
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCita:
                    referencedColumnName: idCita
            orphanRemoval: false
        idpaciente:
            targetEntity: Paciente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPaciente:
                    referencedColumnName: idPaciente
            orphanRemoval: false
    lifecycleCallbacks: {  }
