HC\HCBundle\Entity\Visita:
    type: entity
    table: visita
    indexes:
        idPaciente:
            columns:
                - idPaciente
        idCita:
            columns:
                - idCita
        idMedico:
            columns:
                - idMedico
        idEnfermera:
            columns:
                - idEnfermera
    id:
        idvisita:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: idVisita
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
    manyToOne:
        idpaciente:
            targetEntity: Paciente
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idPaciente:
                    referencedColumnName: idPaciente
            orphanRemoval: false
        idcita:
            targetEntity: Cita
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idCita:
                    referencedColumnName: idCita
            orphanRemoval: false
        idmedico:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idMedico:
                    referencedColumnName: idUsuario
            orphanRemoval: false
        idenfermera:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idEnfermera:
                    referencedColumnName: idUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
