bitacora:
    path:     /
    defaults: { _controller: "HCHCBundle:Bitacora:index" }

bitacora_show:
    path:     /{id}/show
    defaults: { _controller: "HCHCBundle:Bitacora:show" }

bitacora_new:
    path:     /new
    defaults: { _controller: "HCHCBundle:Bitacora:new" }

bitacora_create:
    path:     /create
    defaults: { _controller: "HCHCBundle:Bitacora:create" }
    requirements: { _method: post }

bitacora_edit:
    path:     /{id}/edit
    defaults: { _controller: "HCHCBundle:Bitacora:edit" }

bitacora_update:
    path:     /{id}/update
    defaults: { _controller: "HCHCBundle:Bitacora:update" }
    requirements: { _method: post|put }

bitacora_delete:
    path:     /{id}/delete
    defaults: { _controller: "HCHCBundle:Bitacora:delete" }
    requirements: { _method: post|delete }

bitacora_vaciar:
    path:     /vaciarBitacora
    defaults: { _controller: "HCHCBundle:Bitacora:vaciar" }

